site:
  title: Plentymarkets Developers site 2.0 [EN]
  start_page: developers::homepage.adoc
content:
  sources:
  - url: https://github.com/plentymarkets/plenty-developers-docs
    branches: main
    start_path: docs/en-gb
  - url: https://github.com/plentymarkets/module-version-doc.git
    branches:
      - beta7
      - early
      - stable7
  - url: https://github.com/plentymarkets/docs-raw
    branches:
      - beta7
      - early
      - stable7
  - url: https://github.com/plentymarkets/api-doc
    branches:
      - master
    start_path: plentymarkets/docs
output:
    dir: ./build/en-gb
ui:
  bundle:
    url: https://github.com/plentymarkets/plenty-docs-ui/raw/main/build/ui-bundle.zip
    snapshot: true
