name: CI

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ ContentSourceUpdate, UIBundleUpdate ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: 3113546
          access_token: ${{ secrets.GITHUB_TOKEN }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.x
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true

      - name: Build site
        run: |
          npm i -g @antora/cli @antora/site-generator-default
          antora antora-playbook-de.yml --fetch --stacktrace
          antora antora-playbook-en.yml --fetch --stacktrace
          
      - name: Copy index to build
        run: |
          cp index.html ./build/index.html
          
      - name: Upload site to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          SOURCE_DIR: './build'
          AWS_REGION: 'eu-central-1'
      
      - name: Invalidate CloudFront cache
        uses: awact/cloudfront-action@master
        env:
          SOURCE_PATH: '/*'
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
