name: CI

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.x
          # Set this option if you want the action to check for the latest available version that satisfies the version spec
          check-latest: true

      - name: Build site
        run: |
          npm i -g @antora/cli @antora/site-generator-default
          antora antora-playbook-de.yml --fetch --stacktrace
          antora antora-playbook-en.yml --fetch --stacktrace
          
      - name: Upload site to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'   # optional: defaults to us-east-1
          SOURCE_DIR: './build'      # optional: defaults to entire repository
